# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
  type: mariadb:10.4
  disk: 4096

cache:
  type: redis:5.0

search:
  type: solr:8.6
  disk: 1024
